import { ApolloClient, InMemoryCache } from '@apollo/client'
import Head from 'next/head'
import { useState, useEffect } from 'react';
import { GET_ALL_POSTS } from '../graphql/queries';
import { useRouter } from 'next/router'

export default function Home({ posts }) {
  const [articles, setArticles] = useState([]);
  const router = useRouter();

  useEffect(() => {
    // Replace 'https://your-strapi-app.herokuapp.com' with your actual Strapi app URL
    fetch('https://strapi-gatsby-blog-demo.herokuapp.com/api/articles')
      .then(response => response.json())
      .then(data => {
        console.log(data.data);  // log the data
        setArticles(data.data)
      })
      .catch(error => console.error(error));
  }, []);

  const handleClick = (id) => {
    router.push(`/${id}`)
  }

  return (
    <div>
      <Head>
        <title>My blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
         <div className='header'>
        <div className='headerTitle'>
            <span className='headerTitleSm'> Nextjs & Strapi </span>
            <span className='headerTitleLg'> Blog</span>
        </div>
      <img
          className="headerImg"
          src="https://images.pexels.com/photos/1167355/pexels-photo-1167355.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
          alt=""
        />

        
        </div>
      <h1>Welcome to my Demo Blog</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eu metus turpis. Cras posuere blandit erat, eu maximus erat rutrum ac. Aenean suscipit et ligula nec feugiat. Sed maximus purus nunc, ut sagittis neque placerat ac. </p>
      <br />
      {/* {posts.map((val, i) => {
        return (
          <Link key={i} href={val.attributes.urlSlug}>
            <a>
              <div className="card">
                <h3>{val.attributes.title}</h3>
                <p>{val.attributes.description}</p>
              </div>
            </a>
          </Link>
        )
      })} */}

      <h1>Articles</h1>
      {articles.map((article, i) => (
        <div key={article?.attributes?.id} className="card" onClick={() => handleClick(article?.id)}>
          <a>
            <h2>{article?.attributes?.title}</h2>
            <p>{article?.attributes?.description}</p>
          </a>
        </div>
      ))}
    </div>
  )
}
